FROM python:3.10-slim

WORKDIR /pipeline

# RUN apt-get update && apt-get install -y \
#     gcc \
#     g++ \
#     && rm -rf /var/lib/apt/lists/*

COPY src/train.py .
COPY configs/config.yaml .
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

