FROM python:3.10-slim

WORKDIR /pipeline

COPY src/serve.py .
COPY requirements.txt .
COPY configs/config.yaml .
COPY src/utils.py .


RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 3001

CMD ["python", "serve.py"]