model:
  grace_period: 3
  tau: 0.05
  delta: 1.0e-7
  max_size: 100
  bootstrap_sampling: true

mlflow:
  tracking_uri: "http://mlflow:5000"
  experiment_name: "btc-prediction"
  model_name: "btc-prediction-model"

stream:
  symbol: "BINANCE:BTCUSDT"
  trigger_frequency: 3
  kafka_topic: "stock-recommendations"
  kafka_broker: "kafka:9092"